### ISSUE TITLE
Emits database errors during `core install` for Bedrock installs

### ISSUE THREAD

**Issue by aaemnnosttv** [wp-cli/restful#102]
This problem is probably not limited to Bedrock, but WordPress projects that have a non-standard structure or register additional theme directories.

With the package installed, many database errors are emitted during `wp core install` using a Bedrock project.

See here: [bedrock-install.txt](https://github.com/wp-cli/restful/files/1016513/bedrock-install.txt)

wp-cli/restful wp-cli/restful@5f7130b

**Comment by danielbachhuber** [comment]
> With the package installed, many database errors are emitted during `wp core install` using a Bedrock project.

We can get around this by bailing early in wp-cli/restful if `defined( 'WP_INSTALLING' ) && WP_INSTALLING`
