### ISSUE TITLE
How to load restful in windows

### ISSUE THREAD

**Issue by ashishpatel1992** [wp-cli/restful#105]
How to load restful API in windows as after running command 
`wp --http=http://127.0.0.1/mysite/`
I get Error 
`Error: RESTful WP-CLI needs to be installed. Try 'wp package install wp-cli/restful'.`
Upon installing successfully I get same Error every time
Here is the installation Log

```
Installing package wp-cli/restful (dev-master)
Updating C:\Users\Ashish/.wp-cli/packages/composer.json to require the package...
Using Composer to install the package...
---
Loading composer repositories with package information
Updating dependencies
Resolving dependencies through SAT
Dependency resolution completed in 0.169 seconds
Analyzed 4353 packages to resolve dependencies
Analyzed 168589 rules to resolve dependencies
Package operations: 1 install, 0 updates, 0 removals
Installs: wp-cli/restful:dev-master 4194f57
 - Installing wp-cli/restful (dev-master 4194f57)
Writing lock file
Generating autoload files
---
Success: Package installed.
```
Also tried to place the files in c:\wp-cli\.wp-cli\...
But that too doesn't help. Any solution for Windows Users?

**Comment by miya0001** [comment]
@ashishpatel1992 

Github issues aren't for general support questions, but there are other venues you can try: http://wp-cli.org/#support

Related: #106
