### ISSUE TITLE
Restful API no more work using http

### ISSUE THREAD

**Issue by ashishpatel1992** [wp-cli/restful#106]
I have tried following command wp --http=https://mysite.com/ db check
but shows error
`Error: Couldn't auto-discover WP REST API endpoint from https://mysite.com/.`

**Comment by miya0001** [comment]
Ah, I tried some WordPress site, then I have same issue with one of them.
We have to look into this problem.

@ashishpatel1992 Is #105 same issue? I close #105 , because Github issues aren't for general support questions, but there are other venues you can try: http://wp-cli.org/#support

**Comment by ashishpatel1992** [comment]
#105 is different than this one.

**Comment by miya0001** [comment]
OK, but #105 looks general support, so please see http://wp-cli.org/#support.
But I have same problem with this issue, we will look into more details.

Thanks for bug report. 😄

**Comment by ashishpatel1992** [comment]
Ok I think I found the bug in file wp-cli/restful/inc/Runner.php
Replace Line No. 99
```
		if ( 'rel="https://api.w.org/"' !== trim( $bits[1] ) ) {
```
with
```
		$bits2 = explode(',',$bits[1]);
	if ( 'rel="https://api.w.org/"' !== trim( $bits2[0] ) ) {
```
Since `$bits` variable contains: 
`<https://mysite.com/wp-json/>; rel="https://api.w.org/", <https://mysite.com/>; rel=shortlink`
but the if condition expects
`<https://mysite.com/wp-json/>; rel="https://api.w.org/"; rel=shortlink`
Hope corrections will be updated.

**Comment by miya0001** [comment]
Great! Could you please give us pull-request?
Thanks!

**Comment by ashishpatel1992** [comment]
Sent you a pull #107

**Comment by miya0001** [comment]
Thanks!

**Comment by Daisuke-sama** [comment]
Seems like the error still exists.
When I try to make `wp create config --http=https://mywebsi.te` , I get the same error. Where I can get the answer?
