### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by binaryfire** [wp-cli/restful#119]
Hi guys,

This is exactly what I need for an automation project. Just wondering if this project is still being maintained and if there are plans for further development in the future?

Cheers!

**Comment by R0dri** [comment]
I need this too for the same purposes.

There is an update 5mo ago. But since no one has answered here it seems like this has been kind of abandoned? I will give it a go either way. If it ain't broke you know...

@binaryfire have you find an alternate solution?

**Comment by Basilakis** [comment]
@R0dri what have u done final?

**Comment by alexkuc** [comment]
I guess it is slow in terms of development pace, but I can see that there was a PR merged a couple of months ago.

**Comment by danielbachhuber** [comment]
We're not actively developing `wp-cli/restful` but you're free to use it and submit pull requests for minor improvements.
