### ISSUE TITLE
PHP Warning for missing field. 

### ISSUE THREAD

**Issue by spacedmonkey** [wp-cli/restful#139]
## Bug Report

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

I get the following error. 

```
PHP Warning:  Undefined variable $fields in /Users/jonny/.wp-cli/packages/vendor/wp-cli/restful/inc/RestCommand.php on line 174
```

**Describe how other contributors can replicate this bug**

I make a request like this. 
```
wp rest attachment list --fields=date
```

**Provide a possible solution**

Change this 

```
$items[ $key ] = self::limit_item_to_fields( $item, $fields );
```

to 

```
$items[ $key ] = self::limit_item_to_fields( $item, $assoc_args['fields']);
```

**Comment by danielbachhuber** [comment]
Thanks for the report, @spacedmonkey !

Want to submit a PR for this?
