### ISSUE TITLE
Standalone PHP REST client

### ISSUE THREAD

**Issue by swalkinshaw** [wp-cli/restful#23]
This only occurred to me today after taking a quick look at the codebase, but I realized there's two things being developed here:
1. WP REST API client
2. WP-CLI plugin

Since you're doing most of the hard work for 1., it would be great to have a separate standalone PHP library (and Composer package) that could be used on its own.

This package/plugin could then use the client as a dependency and it would be pretty minimal.

I'd say the main question is around distributing this package. Not sure how WP-CLI packages handle dependencies.

**Comment by danielbachhuber** [comment]
> it would be great to have a separate standalone PHP library (and Composer package) that could be used on its own.

:100: Great idea :)

cc @rmccue @rachelbaker @joehoyle
