### ISSUE TITLE
Package install command fails for restful under certain reproducible circumstances

### ISSUE THREAD

**Issue by dsifford** [wp-cli/restful#88]
Hi there, 

I've tried this command with several other wp-cli packages and it seems to only fail with this package.

this command works perfect:
```sh
wp package install wp-cli/restful --allow-root
```

this command does not:
```sh
wp package install wp-cli/restful --quiet --allow-root
```

any ideas? (note: the `allow-root` is used due to this being done in a docker container on build and I'm being too lazy to create a user and give permissions to that user for the composer directory)

**Comment by danielbachhuber** [comment]
@dsifford Can you share the actual failure please?

**Comment by dsifford** [comment]
Hold on... trying a few more times and I might be wrong... Will report back in just a sec

**Comment by dsifford** [comment]
Yep, disregard... 

![image](https://cloud.githubusercontent.com/assets/5240018/19058554/39eda96c-89a6-11e6-8837-a592ff989c79.png)

Dang typos! :joy: 

Sorry for the unnecessary noise! Thanks for your awesome work on this and wp-cli proper @danielbachhuber :+1:

**Comment by danielbachhuber** [comment]
That would do it :)
