### ISSUE TITLE
travis is failing in before_script stage

### ISSUE THREAD

**Issue by diablodale** [wp-cli/restful#94]
Travis is failing at beginning/core. I've made no changes. Therefore, its something wrong with travis or with the install procedures you configured. Or perhaps travis made changes and now your install procedures are outdated.

The error is:
```
install_db
+mysql -e 'CREATE DATABASE IF NOT EXISTS wp_cli_test;' -uroot
+mysql -e 'GRANT ALL PRIVILEGES ON wp_cli_test.* TO "wp_cli_test"@"localhost" IDENTIFIED BY "password1"' -uroot
0.19s$ ./vendor/bin/behat

[Symfony\Component\DependencyInjection\Exception\ServiceCircularReferenceException]                             
  Circular reference detected for service "gherkin", path: "gherkin -> gherkin.loader.feature_suite -> gherkin".
```

**Comment by danielbachhuber** [comment]
Related https://github.com/wp-cli/scaffold-package-command/issues/79

**Comment by diablodale** [comment]
OK. I'm winding down my current participation in this project. I've fixed all the needed functionality for my immediate needs. I have only a few more changes which I'll commit over the next week.
If in the future travis is working, please contact me or open a ticket to me and I'll fix any code issues on my commits that travis finds.
Also, if travis is updated to have apache, please also contact me and you have my word to update the repro with travis test cases that exercise the code in my commits.

**Comment by danielbachhuber** [comment]
> OK. I'm winding down my current participation in this project. I've fixed all the needed functionality for my immediate needs. I have only a few more changes which I'll commit over the next week.

Sounds good.

> If in the future travis is working, please contact me or open a ticket to me and I'll fix any code issues on my commits that travis finds.

It should be fixed in the near future. The underlying problem is in Symfony: https://github.com/symfony/symfony/issues/21632#issuecomment-280484021

> Also, if travis is updated to have apache, please also contact me and you have my word to update the repro with travis test cases that exercise the code in my commits.

Sounds good, thanks for the offer.

**Comment by danielbachhuber** [comment]
This was fixed upstream.
