### ISSUE TITLE
missing license information

### ISSUE THREAD

**Issue by diablodale** [wp-cli/restful#97]
Standard licensing information is missing from this project.
- I could find it in only one place -- within composer.json having Daniel's name and the license=MIT.
- The LICENSE file is missing
- licensing headers are missing in the two core files implementing restful: inc/RestCommand.php and inc/Runner.php.

Since the composer file in this repro names MIT and the wp-cli repro uses MIT, I suspect the intention is to make claim via the MIT license.

I can add the LICENSE file to have daniel's name as original author of the code and mine as additional author of all my commits; all using the same MIT license. I can also update composer's json to include my name as another author.

If, instead, the license is to be granted by contributors of restful (like done in wp-cli), then please clarify that and I'll use that nomenclature instead and adjust composer.json and a new LICENSE file both -- basically copying the approach of wp-cli.

Please note, attribution and reputation are both important in today's development industry. It is important to me that my code and anyone else's for restful have attribution directly or via a group of which these authors are a member.

**Comment by danielbachhuber** [comment]
> Since the composer file in this repro names MIT and the wp-cli repro uses MIT, I suspect the intention is to make claim via the MIT license.

You are correct — MIT is the intent.

> I can add the LICENSE file to have daniel's name as original author of the code and mine as additional author of all my commits; all using the same MIT license.

Let's go with the more generic:

```
Copyright (C) 2011-2017 WP-CLI Development Group 
```

**Comment by diablodale** [comment]
The "2011-2017 WP-CLI Development Group" ". Isn't correct legally or in spirit.
- legal example: you can not copyright any further back than 2015. restful didn't exist before then.
- spirit: does not include contributors to the project "restful" but not the project "wp-cli" nor does it provide a manner to find how who the contributors are

I recommend the following and this is an alignment with (c) approach of wp-cli
```
Copyright (C) 2015-2017 WP-CLI Restful Development Contributors (https://github.com/wp-cli/restful/graphs/contributors)
```
